server:
  port: 9005
spring:
  application:
    name: tensquare-gathering
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.49.66:3306/tensquare_gathering?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
  redis:
    host: 10.10.49.66