server:
  port: 9002
spring:
  application:
    name: tensquare_recruit
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.49.66:3306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true