server:
  port: 9008
spring:
  application:
    name: tensquare-user
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.49.66:3306/tensquare_user?characterEncoding=utf-8
    username: root
    password: 123456
  data:
    jpa:
      database: MySQL
      show-sql: true
      generate-ddl: true
    redis:
      host: 10.10.49.66
    rabbitmq:
      host: 10.10.49.66
jwt:
  config:
    key: xxw
    ttl: 3600000
